apiVersion: v1
kind: Service
metadata:
  labels:
    run: connector-service-deployment
  name: connector-service-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: connector-deployment
  type: NodePort
