ALTER TABLE connector
ADD COLUMN "version" INT4 NOT NULL,
ADD COLUMN status VARCHAR(128),
ADD COLUMN category VARCHAR(128),
ADD COLUMN shared BOOLEAN DEFAULT FALSE;

ALTER TABLE service
DROP COLUMN node,
DROP COLUMN published,
ADD COLUMN status varchar(128),
ADD COLUMN config JSONB,
ADD COLUMN flow JSONB,
ADD COLUMN trigger VARCHAR(128);