apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: connector-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: connector-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
